{% set version = "3.0.0" %}
{% set name = "zict" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e321e263b6a97aafc0790c3cfb3c04656b7066e6738c37fffcca95d803c9fba5

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - heapdict
    - python-lmdb

{% set tests_to_skip = "" %}
# Skipping unnecesssary tests below as a result of low disk space on for win-64 causing build failures.
{% set tests_to_skip = tests_to_skip + "test_mapping" %}   #  [win]
{% set tests_to_skip = tests_to_skip + " or test_reuse" %}    #  [win]
{% set tests_to_skip = tests_to_skip + " or test_creates_dir" %}   #  [win]

test:
  imports:
    - zict
  source_files:
    - zict/tests
  requires:
    - pip
    - pytest
    # for tests/test_async_buffer.py
    - pytest-asyncio
  commands:
    - pip check
    - pytest  # [not win]
    - pytest zict/tests -k "not ({{ tests_to_skip }})"  # [win or py<314]
    - pytest zict/tests -k "not ({{ tests_to_skip }})" --ignore=zict/tests/test_lmdb.py --ignore=zict/tests/test_lru.py  # [win or py==314]

about:
  home: https://github.com/mrocklin/zict
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Mutable Mapping tools.
  summary: Composable Dictionary Classes
  dev_url: https://github.com/dask/zict
  doc_url: https://zict.readthedocs.io/

extra:
  recipe-maintainers:
    - mrocklin
    - jrbourbeau
