{% set version = "0.1.1" %}
{% set name = "zict" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4e2758d8f202a5bb7fd94f45b87cccf2092bfc97786cc0c8321ab35d72e098a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - heapdict

test:
  imports:
    - zict

about:
  home: http://github.com/mrocklin/zict
  license: BSD 3-Clause
  summary: 'Composable Dictionary Classes'

extra:
  recipe-maintainers:
    - mrocklin
    - pitrou
