travis:
  secure:
    BINSTAR_TOKEN: jzYSF24OuIcjjtrOnuNsNfjOUXpCXCxQ06vBEehFlcQ1X/5wssi98VeIbw25m03rMmaIgAtlh1/MyGpI/mfESvhN1nkkRhCWGL4UVOnJ8uij39sZZDOTPoCNM8PwddhtqdOC568SWrPtvf4NYiNqoACZ2oz/v+coOy0yElP5RJMbz0ADz+bMDEUfiXls750DqJUq+71tLNBLnbrQyMPOWEDeDWDV5ehPawX960mCCa2fHeYiN1f8u3P/92SLDTMv4GqMvh5aaspNCIlikCDa8Q2GTppjWkVpwvO0EKSzC9eyUwjr2smhzOI4HPH47VliApcmsy2sHl1shwUwsrDACwv6G1QOWDvJwOLaiSY6cl4sSj5i0Xu4E+PqOMRlF1RIIHdsmSVL0B+os1StQS38QSbnJGQQ28Bph7myNp6xGL2LGxiC/3L5QjdQawFDE2KBIKUL6OClbL4pQ4OF2ddkUHzQZbGxmN8bF1P8TFbP/TXv1I8SJh283CiBA7m6tBsA+LkNI5E4tqkLVj0234x4hxNV1uBU2Du+lE4SvAWoqBLr6Q5mhDSDl8becmLKpoUba7e2m2Cdf0oi3rE5BKx5IXegY7LWJjgAziyAYMIztTtBalzT5fipB62SNfXdX7eArX58UucHiM5hTqkCRuvhIpTFuxkszeL8EIuj8nAOXm4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
