travis:
  secure:
    BINSTAR_TOKEN: Na6G05Vv8hmnYLmuEzbtjIOVQ4R8gLWXle2YClLA80ZgtSnVZjrExkXTgnhdIWZ6Yds23wVqBnQvSYnXDrjMCH/AUEkQpue393s2mhpLyjX/exJEXSTUqySg0BrgcUe6MUB3ZJpKMPtBeDzOjKrFCbdNhSnhaHthX50wHfjt/xrclBGP5KW73vEJBEi20gOmHUMKdAzPQf/PKC4Pv/LLsmSqgfsHtV5grazb6fdRZHsPi3NpQ3wAUAGLL8fuJxSI0B6JcJqsUt1jIZW3DSycwTc0RKaAzTVCEAyd8oyL/M/gFqZj9G6E8PZN1CfV83J9wP5CR4KepWxdpJyvl0AwSAiYDh7a/403Sc6R03izSAodzgL6DEXttSYFseUDHcRG0oivpmfaTPQzj5TBUXyz7sEcfcfJh0wnVmfClZVvzgAurNIxa6VcP4nxDEtj0lQw/hZq4H2vTz15cxKQULKI7KIfwpya7DsuDWwfyhSuylU+PbYJeS+AgWSzg5nOT5zxn1RWo1YlRF05GIF8XvKwJj3A9J78Tvy9sNJ3PAPLVJslfpjlDJEKBShjK3AgW4NbOsFyuZEOrT/k8uvTD7Pnzcry34tFnTf+d/7dpakjfQsCUwHuBS6OfsiLHttWKYg1j2bT99s96ohxOYOlbddftmEr8h64V+mnNMhLbeM/8Ss=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
